### ISSUE TITLE
Set an empty Array will cause RWFileCache::get() return a string like "a:0:{}"

### ISSUE THREAD

**Issue by kum1ko** [rapidwebltd/RW-File-Cache#6]
$cache->set('key', []); // bool(true)
$cache->get('key', []); // string(6) "a:0:{}"

RWFileCache.php on line 115
$unserializedContent = @unserialize($content)
This is bool(false) when @unserialize($content) return []

**Comment by Jord-JD** [comment]
Good catch, thanks!

I'll get this fixed.

**Comment by Jord-JD** [comment]
Fixed in release 1.0.1. :smile:
