### ISSUE TITLE
Windows servers unimplemented sys_getloadavg

### ISSUE THREAD

**Issue by m1egalius** [rapidwebltd/RW-File-Cache#8]
On windows servers you will get error:
`Fatal error: Uncaught Error: Call to undefined function rapidweb\RWFileCache\sys_getloadavg() `

RWFileCache.php, line 115

Should be possible to disable through config (like `unixLoadUpperThreshold` set to zero)

**Comment by Jord-JD** [comment]
I'm going to look into this, but I'll probably use `-1` as the value to disable this feature.

A value of `0` might be handy for people who want to temporarily lock down their cache to only use stale files.

**Comment by Jord-JD** [comment]
So this was pretty easy.

I've just released v1.1.0 which should hopefully solve your issue. Give it a try, and get back to us.

**Comment by Jord-JD** [comment]
@m1egalius Can you confirm if this fixes your issue?

**Comment by Jord-JD** [comment]
Closing. Assumed fixed.
